apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace.name }}-configmap
  namespace: {{ .Values.namespace.name }}
data:
  backend_url: {{ .Values.host_ip.name }}-service:{{ .Values.host_ip.port }}
